### ISSUE TITLE
Traceback with newer zope (4.5.1)

### ISSUE THREAD

**Issue by gforcada** [collective/collective.xmltestreport#26]
This traceback happens right after printing the test totals, after that, it tries to write the XML report that jenkins, or other CI, can use to make visualizations and graphs out of it.

```
Traceback (most recent call last):
  File "bin/jenkins-test", line 350, in <module>
    '--test-path', '/home/jenkins/workspace/plone-next/src/freitag.util.validators/src',
  File "/home/jenkins/.buildout/eggs/cp27m/collective.xmltestreport-2.0.2-py2.7.egg/collective/xmltestreport/runner.py", line 66, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/cp27m/collective.xmltestreport-2.0.2-py2.7.egg/collective/xmltestreport/runner.py", line 83, in run_internal
    runner.options.output.writeXMLReports()
  File "/home/jenkins/.buildout/eggs/cp27m/collective.xmltestreport-2.0.2-py2.7.egg/collective/xmltestreport/formatter.py", line 258, in writeXMLReports
    errorMessage = str(excInstance)
  File "/home/jenkins/.buildout/eggs/cp27m/Chameleon-3.8.1-py2.7.egg/chameleon/exc.py", line 275, in __call__
    for name, value in self._kwargs.items()
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.5.1-py2.7.egg/OFS/SimpleItem.py", line 87, in __repr__
    return super(PathReprProvider, self).__repr__()
TypeError: descriptor '__repr__' for 'persistent.Persistent' objects doesn't apply to 'Acquisition.ImplicitAcquisitionWrapper' object
```

No idea what `Persistent` object can be :shrug:

**Comment by gforcada** [comment]
Seems it did not happen to many others 😅
